[platformio]
src_dir = esp32_rtsp_mic_birdnetgo

[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino

monitor_speed = 115200

lib_deps =
    tzapu/WiFiManager @ ^2.0.17
    knolleary/PubSubClient @ ^2.8

